version: '3'
services:
  frontend:
    build: .
    volumes:
      - ./:/var/www/project
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    tty: yes
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_DATABASE: main
    volumes:
      - ./data/db:/docker-entrypoint-initdb.d
    ports:
      - 33066:3306
